// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/notification_event.proto

package notification_eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==============================
// Common types
// ==============================
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3"  json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3"  json:"lng,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3"  json:"address,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_notification_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DriverInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3"  json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3"  json:"avatar_url,omitempty"`
	CarType       string                 `protobuf:"bytes,4,opt,name=car_type,json=carType,proto3"  json:"car_type,omitempty"`
	CarPlate      string                 `protobuf:"bytes,5,opt,name=car_plate,json=carPlate,proto3"  json:"car_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	mi := &file_proto_notification_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{1}
}

func (x *DriverInfo) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DriverInfo) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *DriverInfo) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

// ==============================
// From Matching Service -> Notification Service
// ==============================
type MatchingEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RouteId                 string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"  json:"user_id,omitempty"`
	Status                  string                 `protobuf:"bytes,3,opt,name=status,proto3"  json:"status,omitempty"` // success / no_driver / driver_cancelled
	Driver                  *DriverInfo            `protobuf:"bytes,4,opt,name=driver,proto3"  json:"driver,omitempty"`
	PickupLocation          *Location              `protobuf:"bytes,5,opt,name=pickup_location,json=pickupLocation,proto3"  json:"pickup_location,omitempty"`
	DropoffLocation         *Location              `protobuf:"bytes,6,opt,name=dropoff_location,json=dropoffLocation,proto3"  json:"dropoff_location,omitempty"`
	Price                   float64                `protobuf:"fixed64,7,opt,name=price,proto3"  json:"price,omitempty"`
	DistanceDriverToPickup  float64                `protobuf:"fixed64,8,opt,name=distance_driver_to_pickup,json=distanceDriverToPickup,proto3"  json:"distance_driver_to_pickup,omitempty"`    // ระยะทางคนขับไปจุดรับ
	DistancePickupToDropoff float64                `protobuf:"fixed64,9,opt,name=distance_pickup_to_dropoff,json=distancePickupToDropoff,proto3"  json:"distance_pickup_to_dropoff,omitempty"` // ระยะทางจุดรับถึงจุดส่ง
	DurationTotalSec        int32                  `protobuf:"varint,10,opt,name=duration_total_sec,json=durationTotalSec,proto3"  json:"duration_total_sec,omitempty"`                        // เวลารวมวินาที
	RoutePolyline           string                 `protobuf:"bytes,11,opt,name=route_polyline,json=routePolyline,proto3"  json:"route_polyline,omitempty"`                                    // เส้นทาง map
	Timestamp               int64                  `protobuf:"varint,12,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`                                                                // Unix timestamp ของ event
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MatchingEvent) Reset() {
	*x = MatchingEvent{}
	mi := &file_proto_notification_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingEvent) ProtoMessage() {}

func (x *MatchingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingEvent.ProtoReflect.Descriptor instead.
func (*MatchingEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{2}
}

func (x *MatchingEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *MatchingEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchingEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchingEvent) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *MatchingEvent) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *MatchingEvent) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *MatchingEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MatchingEvent) GetDistanceDriverToPickup() float64 {
	if x != nil {
		return x.DistanceDriverToPickup
	}
	return 0
}

func (x *MatchingEvent) GetDistancePickupToDropoff() float64 {
	if x != nil {
		return x.DistancePickupToDropoff
	}
	return 0
}

func (x *MatchingEvent) GetDurationTotalSec() int32 {
	if x != nil {
		return x.DurationTotalSec
	}
	return 0
}

func (x *MatchingEvent) GetRoutePolyline() string {
	if x != nil {
		return x.RoutePolyline
	}
	return ""
}

func (x *MatchingEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Driver Accepted Event (Driver UI -> Notification Service)
// ==============================
type DriverAcceptedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	Driver        *DriverInfo            `protobuf:"bytes,3,opt,name=driver,proto3"  json:"driver,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverAcceptedEvent) Reset() {
	*x = DriverAcceptedEvent{}
	mi := &file_proto_notification_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAcceptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAcceptedEvent) ProtoMessage() {}

func (x *DriverAcceptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAcceptedEvent.ProtoReflect.Descriptor instead.
func (*DriverAcceptedEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{3}
}

func (x *DriverAcceptedEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DriverAcceptedEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverAcceptedEvent) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *DriverAcceptedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Cancellation Event (Driver / Passenger cancels)
// ==============================
type CancellationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3"  json:"cancelled_by,omitempty"` // "driver" or "passenger"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3"  json:"reason,omitempty"`                              // optional ข้อความเหตุผล
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancellationEvent) Reset() {
	*x = CancellationEvent{}
	mi := &file_proto_notification_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancellationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancellationEvent) ProtoMessage() {}

func (x *CancellationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancellationEvent.ProtoReflect.Descriptor instead.
func (*CancellationEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{4}
}

func (x *CancellationEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CancellationEvent) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *CancellationEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancellationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Notification Service -> Driver Service
// ==============================
type DriverAssignmentEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RouteId         string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	DriverId        string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3"  json:"status,omitempty"` // "assigned" | "cancelled"
	PickupLocation  *Location              `protobuf:"bytes,4,opt,name=pickup_location,json=pickupLocation,proto3"  json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,5,opt,name=dropoff_location,json=dropoffLocation,proto3"  json:"dropoff_location,omitempty"`
	Price           float64                `protobuf:"fixed64,6,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriverAssignmentEvent) Reset() {
	*x = DriverAssignmentEvent{}
	mi := &file_proto_notification_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAssignmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAssignmentEvent) ProtoMessage() {}

func (x *DriverAssignmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAssignmentEvent.ProtoReflect.Descriptor instead.
func (*DriverAssignmentEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{5}
}

func (x *DriverAssignmentEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DriverAssignmentEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverAssignmentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverAssignmentEvent) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *DriverAssignmentEvent) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *DriverAssignmentEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DriverAssignmentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Notification Service -> Travel Service
// ==============================
type TravelUpdateEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RouteId         string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3"  json:"status,omitempty"` // "matched" | "cancelled"
	DriverId        string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	PickupLocation  *Location              `protobuf:"bytes,4,opt,name=pickup_location,json=pickupLocation,proto3"  json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,5,opt,name=dropoff_location,json=dropoffLocation,proto3"  json:"dropoff_location,omitempty"`
	Price           float64                `protobuf:"fixed64,6,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TravelUpdateEvent) Reset() {
	*x = TravelUpdateEvent{}
	mi := &file_proto_notification_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelUpdateEvent) ProtoMessage() {}

func (x *TravelUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelUpdateEvent.ProtoReflect.Descriptor instead.
func (*TravelUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{6}
}

func (x *TravelUpdateEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *TravelUpdateEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TravelUpdateEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TravelUpdateEvent) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *TravelUpdateEvent) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *TravelUpdateEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TravelUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Notification Service -> Passenger UI
// ==============================
type PassengerNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RouteId         string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3"  json:"status,omitempty"` // "driver_assigned" | "driver_cancelled" | "passenger_cancelled"
	Driver          *DriverInfo            `protobuf:"bytes,3,opt,name=driver,proto3"  json:"driver,omitempty"`
	PickupLocation  *Location              `protobuf:"bytes,4,opt,name=pickup_location,json=pickupLocation,proto3"  json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,5,opt,name=dropoff_location,json=dropoffLocation,proto3"  json:"dropoff_location,omitempty"`
	Price           float64                `protobuf:"fixed64,6,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	CancelledBy     string                 `protobuf:"bytes,8,opt,name=cancelled_by,json=cancelledBy,proto3"  json:"cancelled_by,omitempty"`    // optional
	CancelReason    string                 `protobuf:"bytes,9,opt,name=cancel_reason,json=cancelReason,proto3"  json:"cancel_reason,omitempty"` // optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PassengerNotification) Reset() {
	*x = PassengerNotification{}
	mi := &file_proto_notification_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerNotification) ProtoMessage() {}

func (x *PassengerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerNotification.ProtoReflect.Descriptor instead.
func (*PassengerNotification) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{7}
}

func (x *PassengerNotification) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *PassengerNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PassengerNotification) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *PassengerNotification) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *PassengerNotification) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *PassengerNotification) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PassengerNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PassengerNotification) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *PassengerNotification) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

// ==============================
// Notification Service -> Driver UI
// ==============================
type DriverNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3"  json:"status,omitempty"`                                 // "assigned" | "cancelled"
	CancelledBy   string                 `protobuf:"bytes,3,opt,name=cancelled_by,json=cancelledBy,proto3"  json:"cancelled_by,omitempty"`    // optional
	CancelReason  string                 `protobuf:"bytes,4,opt,name=cancel_reason,json=cancelReason,proto3"  json:"cancel_reason,omitempty"` // optional
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverNotification) Reset() {
	*x = DriverNotification{}
	mi := &file_proto_notification_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverNotification) ProtoMessage() {}

func (x *DriverNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverNotification.ProtoReflect.Descriptor instead.
func (*DriverNotification) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{8}
}

func (x *DriverNotification) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DriverNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverNotification) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *DriverNotification) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *DriverNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==============================
// Optional Ack response (Kafka/MQTT)
// ==============================
type NotificationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3"  json:"status,omitempty"`   // "received" | "processed"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3"  json:"message,omitempty"` // optional descriptive message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAck) Reset() {
	*x = NotificationAck{}
	mi := &file_proto_notification_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAck) ProtoMessage() {}

func (x *NotificationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAck.ProtoReflect.Descriptor instead.
func (*NotificationAck) Descriptor() ([]byte, []int) {
	return file_proto_notification_event_proto_rawDescGZIP(), []int{9}
}

func (x *NotificationAck) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *NotificationAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notification_event_proto protoreflect.FileDescriptor

const file_proto_notification_event_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/notification_event.proto\x12\bmatching\"H\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x94\x01\n" +
	"\n" +
	"DriverInfo\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bcar_type\x18\x04 \x01(\tR\acarType\x12\x1b\n" +
	"\tcar_plate\x18\x05 \x01(\tR\bcarPlate\"\x86\x04\n" +
	"\rMatchingEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\x06driver\x18\x04 \x01(\v2\x14.matching.DriverInfoR\x06driver\x12;\n" +
	"\x0fpickup_location\x18\x05 \x01(\v2\x12.matching.LocationR\x0epickupLocation\x12=\n" +
	"\x10dropoff_location\x18\x06 \x01(\v2\x12.matching.LocationR\x0fdropoffLocation\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x129\n" +
	"\x19distance_driver_to_pickup\x18\b \x01(\x01R\x16distanceDriverToPickup\x12;\n" +
	"\x1adistance_pickup_to_dropoff\x18\t \x01(\x01R\x17distancePickupToDropoff\x12,\n" +
	"\x12duration_total_sec\x18\n" +
	" \x01(\x05R\x10durationTotalSec\x12%\n" +
	"\x0eroute_polyline\x18\v \x01(\tR\rroutePolyline\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestamp\"\x99\x01\n" +
	"\x13DriverAcceptedEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12,\n" +
	"\x06driver\x18\x03 \x01(\v2\x14.matching.DriverInfoR\x06driver\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x87\x01\n" +
	"\x11CancellationEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x97\x02\n" +
	"\x15DriverAssignmentEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12;\n" +
	"\x0fpickup_location\x18\x04 \x01(\v2\x12.matching.LocationR\x0epickupLocation\x12=\n" +
	"\x10dropoff_location\x18\x05 \x01(\v2\x12.matching.LocationR\x0fdropoffLocation\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\x93\x02\n" +
	"\x11TravelUpdateEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12;\n" +
	"\x0fpickup_location\x18\x04 \x01(\v2\x12.matching.LocationR\x0epickupLocation\x12=\n" +
	"\x10dropoff_location\x18\x05 \x01(\v2\x12.matching.LocationR\x0fdropoffLocation\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xf0\x02\n" +
	"\x15PassengerNotification\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x06driver\x18\x03 \x01(\v2\x14.matching.DriverInfoR\x06driver\x12;\n" +
	"\x0fpickup_location\x18\x04 \x01(\v2\x12.matching.LocationR\x0epickupLocation\x12=\n" +
	"\x10dropoff_location\x18\x05 \x01(\v2\x12.matching.LocationR\x0fdropoffLocation\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12!\n" +
	"\fcancelled_by\x18\b \x01(\tR\vcancelledBy\x12#\n" +
	"\rcancel_reason\x18\t \x01(\tR\fcancelReason\"\xad\x01\n" +
	"\x12DriverNotification\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcancelled_by\x18\x03 \x01(\tR\vcancelledBy\x12#\n" +
	"\rcancel_reason\x18\x04 \x01(\tR\fcancelReason\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"^\n" +
	"\x0fNotificationAck\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageBYZWdift_backend_go/notification-service/proto/pb/notification_eventpb;notification_eventpbb\x06proto3"

var (
	file_proto_notification_event_proto_rawDescOnce sync.Once
	file_proto_notification_event_proto_rawDescData []byte
)

func file_proto_notification_event_proto_rawDescGZIP() []byte {
	file_proto_notification_event_proto_rawDescOnce.Do(func() {
		file_proto_notification_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_event_proto_rawDesc), len(file_proto_notification_event_proto_rawDesc)))
	})
	return file_proto_notification_event_proto_rawDescData
}

var file_proto_notification_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_notification_event_proto_goTypes = []any{
	(*Location)(nil),              // 0: matching.Location
	(*DriverInfo)(nil),            // 1: matching.DriverInfo
	(*MatchingEvent)(nil),         // 2: matching.MatchingEvent
	(*DriverAcceptedEvent)(nil),   // 3: matching.DriverAcceptedEvent
	(*CancellationEvent)(nil),     // 4: matching.CancellationEvent
	(*DriverAssignmentEvent)(nil), // 5: matching.DriverAssignmentEvent
	(*TravelUpdateEvent)(nil),     // 6: matching.TravelUpdateEvent
	(*PassengerNotification)(nil), // 7: matching.PassengerNotification
	(*DriverNotification)(nil),    // 8: matching.DriverNotification
	(*NotificationAck)(nil),       // 9: matching.NotificationAck
}
var file_proto_notification_event_proto_depIdxs = []int32{
	1,  // 0: matching.MatchingEvent.driver:type_name -> matching.DriverInfo
	0,  // 1: matching.MatchingEvent.pickup_location:type_name -> matching.Location
	0,  // 2: matching.MatchingEvent.dropoff_location:type_name -> matching.Location
	1,  // 3: matching.DriverAcceptedEvent.driver:type_name -> matching.DriverInfo
	0,  // 4: matching.DriverAssignmentEvent.pickup_location:type_name -> matching.Location
	0,  // 5: matching.DriverAssignmentEvent.dropoff_location:type_name -> matching.Location
	0,  // 6: matching.TravelUpdateEvent.pickup_location:type_name -> matching.Location
	0,  // 7: matching.TravelUpdateEvent.dropoff_location:type_name -> matching.Location
	1,  // 8: matching.PassengerNotification.driver:type_name -> matching.DriverInfo
	0,  // 9: matching.PassengerNotification.pickup_location:type_name -> matching.Location
	0,  // 10: matching.PassengerNotification.dropoff_location:type_name -> matching.Location
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_notification_event_proto_init() }
func file_proto_notification_event_proto_init() {
	if File_proto_notification_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_event_proto_rawDesc), len(file_proto_notification_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_event_proto_goTypes,
		DependencyIndexes: file_proto_notification_event_proto_depIdxs,
		MessageInfos:      file_proto_notification_event_proto_msgTypes,
	}.Build()
	File_proto_notification_event_proto = out.File
	file_proto_notification_event_proto_goTypes = nil
	file_proto_notification_event_proto_depIdxs = nil
}
