// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/notification_to_driver.proto

package notification_driverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3"  json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3"  json:"lng,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3"  json:"address,omitempty"` // Optional human-readable address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_notification_to_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_to_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_notification_to_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Event ที่ Notification Service ส่งไป Driver Service
type DriverAssignmentEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RouteId  string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`    // Route id
	DriverId string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"` // Driver id
	Status   string                 `protobuf:"bytes,3,opt,name=status,proto3"  json:"status,omitempty"`                     // assigned, cancelled, pending etc.
	// User info (passenger)
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3"  json:"user_id,omitempty"`
	// Pickup / Dropoff
	PickupLocation  *Location `protobuf:"bytes,5,opt,name=pickup_location,json=pickupLocation,proto3"  json:"pickup_location,omitempty"`
	DropoffLocation *Location `protobuf:"bytes,6,opt,name=dropoff_location,json=dropoffLocation,proto3"  json:"dropoff_location,omitempty"`
	// Pricing info
	Price         float64 `protobuf:"fixed64,7,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp     int64   `protobuf:"varint,8,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverAssignmentEvent) Reset() {
	*x = DriverAssignmentEvent{}
	mi := &file_proto_notification_to_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAssignmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAssignmentEvent) ProtoMessage() {}

func (x *DriverAssignmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_to_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAssignmentEvent.ProtoReflect.Descriptor instead.
func (*DriverAssignmentEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_to_driver_proto_rawDescGZIP(), []int{1}
}

func (x *DriverAssignmentEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DriverAssignmentEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverAssignmentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverAssignmentEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverAssignmentEvent) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *DriverAssignmentEvent) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *DriverAssignmentEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DriverAssignmentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_notification_to_driver_proto protoreflect.FileDescriptor

const file_proto_notification_to_driver_proto_rawDesc = "" +
	"\n" +
	"\"proto/notification_to_driver.proto\x12\x06driver\"H\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xac\x02\n" +
	"\x15DriverAssignmentEvent\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x129\n" +
	"\x0fpickup_location\x18\x05 \x01(\v2\x10.driver.LocationR\x0epickupLocation\x12;\n" +
	"\x10dropoff_location\x18\x06 \x01(\v2\x10.driver.LocationR\x0fdropoffLocation\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestampB[ZYdift_backend_go/notification-service/proto/pb/notification_driverpb;notification_driverpbb\x06proto3"

var (
	file_proto_notification_to_driver_proto_rawDescOnce sync.Once
	file_proto_notification_to_driver_proto_rawDescData []byte
)

func file_proto_notification_to_driver_proto_rawDescGZIP() []byte {
	file_proto_notification_to_driver_proto_rawDescOnce.Do(func() {
		file_proto_notification_to_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_to_driver_proto_rawDesc), len(file_proto_notification_to_driver_proto_rawDesc)))
	})
	return file_proto_notification_to_driver_proto_rawDescData
}

var file_proto_notification_to_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_notification_to_driver_proto_goTypes = []any{
	(*Location)(nil),              // 0: driver.Location
	(*DriverAssignmentEvent)(nil), // 1: driver.DriverAssignmentEvent
}
var file_proto_notification_to_driver_proto_depIdxs = []int32{
	0, // 0: driver.DriverAssignmentEvent.pickup_location:type_name -> driver.Location
	0, // 1: driver.DriverAssignmentEvent.dropoff_location:type_name -> driver.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_notification_to_driver_proto_init() }
func file_proto_notification_to_driver_proto_init() {
	if File_proto_notification_to_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_to_driver_proto_rawDesc), len(file_proto_notification_to_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_to_driver_proto_goTypes,
		DependencyIndexes: file_proto_notification_to_driver_proto_depIdxs,
		MessageInfos:      file_proto_notification_to_driver_proto_msgTypes,
	}.Build()
	File_proto_notification_to_driver_proto = out.File
	file_proto_notification_to_driver_proto_goTypes = nil
	file_proto_notification_to_driver_proto_depIdxs = nil
}
