// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/notification_ui.proto

package notification_uipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------------------------
// Status enum สำหรับ Driver UI
type DriverStatus int32

const (
	DriverStatus_WAITING_FOR_ACCEPT DriverStatus = 0
	DriverStatus_ASSIGNED           DriverStatus = 1
	DriverStatus_ACCEPTED           DriverStatus = 2
	DriverStatus_CANCELLED          DriverStatus = 3
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "WAITING_FOR_ACCEPT",
		1: "ASSIGNED",
		2: "ACCEPTED",
		3: "CANCELLED",
	}
	DriverStatus_value = map[string]int32{
		"WAITING_FOR_ACCEPT": 0,
		"ASSIGNED":           1,
		"ACCEPTED":           2,
		"CANCELLED":          3,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_ui_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_proto_notification_ui_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{0}
}

// -----------------------------
// Status enum สำหรับ Passenger UI
type PassengerStatus int32

const (
	PassengerStatus_DRIVER_ASSIGNED PassengerStatus = 0
	PassengerStatus_DRIVER_ARRIVED  PassengerStatus = 1
	PassengerStatus_COMPLETED       PassengerStatus = 2
)

// Enum value maps for PassengerStatus.
var (
	PassengerStatus_name = map[int32]string{
		0: "DRIVER_ASSIGNED",
		1: "DRIVER_ARRIVED",
		2: "COMPLETED",
	}
	PassengerStatus_value = map[string]int32{
		"DRIVER_ASSIGNED": 0,
		"DRIVER_ARRIVED":  1,
		"COMPLETED":       2,
	}
)

func (x PassengerStatus) Enum() *PassengerStatus {
	p := new(PassengerStatus)
	*p = x
	return p
}

func (x PassengerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PassengerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_ui_proto_enumTypes[1].Descriptor()
}

func (PassengerStatus) Type() protoreflect.EnumType {
	return &file_proto_notification_ui_proto_enumTypes[1]
}

func (x PassengerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PassengerStatus.Descriptor instead.
func (PassengerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{1}
}

// -----------------------------
// Location info ใช้ซ้ำได้ทั้ง UI
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3"  json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3"  json:"lng,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3"  json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_notification_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// ข้อมูลสำหรับ UI คนขับ
type DriverNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"  json:"user_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	DriverName    string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3"  json:"driver_name,omitempty"`
	Status        DriverStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=ui.DriverStatus"  json:"status,omitempty"`
	Pickup        *Location              `protobuf:"bytes,6,opt,name=pickup,proto3"  json:"pickup,omitempty"`
	Dropoff       *Location              `protobuf:"bytes,7,opt,name=dropoff,proto3"  json:"dropoff,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverNotification) Reset() {
	*x = DriverNotification{}
	mi := &file_proto_notification_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverNotification) ProtoMessage() {}

func (x *DriverNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverNotification.ProtoReflect.Descriptor instead.
func (*DriverNotification) Descriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{1}
}

func (x *DriverNotification) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DriverNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverNotification) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverNotification) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DriverNotification) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_WAITING_FOR_ACCEPT
}

func (x *DriverNotification) GetPickup() *Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *DriverNotification) GetDropoff() *Location {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *DriverNotification) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DriverNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ข้อมูลสำหรับ UI ผู้โดยสาร
type PassengerNotification struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	RouteId       string                            `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3"  json:"route_id,omitempty"`
	Status        PassengerStatus                   `protobuf:"varint,2,opt,name=status,proto3,enum=ui.PassengerStatus"  json:"status,omitempty"`
	Driver        *PassengerNotification_DriverInfo `protobuf:"bytes,3,opt,name=driver,proto3"  json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerNotification) Reset() {
	*x = PassengerNotification{}
	mi := &file_proto_notification_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerNotification) ProtoMessage() {}

func (x *PassengerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerNotification.ProtoReflect.Descriptor instead.
func (*PassengerNotification) Descriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{2}
}

func (x *PassengerNotification) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *PassengerNotification) GetStatus() PassengerStatus {
	if x != nil {
		return x.Status
	}
	return PassengerStatus_DRIVER_ASSIGNED
}

func (x *PassengerNotification) GetDriver() *PassengerNotification_DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

// ข้อมูลคนขับ
type PassengerNotification_DriverInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3"  json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3"  json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3"  json:"avatar_url,omitempty"`
	CarType       string                 `protobuf:"bytes,4,opt,name=car_type,json=carType,proto3"  json:"car_type,omitempty"`
	CarPlate      string                 `protobuf:"bytes,5,opt,name=car_plate,json=carPlate,proto3"  json:"car_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerNotification_DriverInfo) Reset() {
	*x = PassengerNotification_DriverInfo{}
	mi := &file_proto_notification_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerNotification_DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerNotification_DriverInfo) ProtoMessage() {}

func (x *PassengerNotification_DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerNotification_DriverInfo.ProtoReflect.Descriptor instead.
func (*PassengerNotification_DriverInfo) Descriptor() ([]byte, []int) {
	return file_proto_notification_ui_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PassengerNotification_DriverInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PassengerNotification_DriverInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PassengerNotification_DriverInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PassengerNotification_DriverInfo) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *PassengerNotification_DriverInfo) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

var File_proto_notification_ui_proto protoreflect.FileDescriptor

const file_proto_notification_ui_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/notification_ui.proto\x12\x02ui\"H\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xb2\x02\n" +
	"\x12DriverNotification\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.ui.DriverStatusR\x06status\x12$\n" +
	"\x06pickup\x18\x06 \x01(\v2\f.ui.LocationR\x06pickup\x12&\n" +
	"\adropoff\x18\a \x01(\v2\f.ui.LocationR\adropoff\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\xa7\x02\n" +
	"\x15PassengerNotification\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.ui.PassengerStatusR\x06status\x12<\n" +
	"\x06driver\x18\x03 \x01(\v2$.ui.PassengerNotification.DriverInfoR\x06driver\x1a\x87\x01\n" +
	"\n" +
	"DriverInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bcar_type\x18\x04 \x01(\tR\acarType\x12\x1b\n" +
	"\tcar_plate\x18\x05 \x01(\tR\bcarPlate*Q\n" +
	"\fDriverStatus\x12\x16\n" +
	"\x12WAITING_FOR_ACCEPT\x10\x00\x12\f\n" +
	"\bASSIGNED\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03*I\n" +
	"\x0fPassengerStatus\x12\x13\n" +
	"\x0fDRIVER_ASSIGNED\x10\x00\x12\x12\n" +
	"\x0eDRIVER_ARRIVED\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02BSZQdift_backend_go/notification-service/proto/pb/notification_uipb;notification_uipbb\x06proto3"

var (
	file_proto_notification_ui_proto_rawDescOnce sync.Once
	file_proto_notification_ui_proto_rawDescData []byte
)

func file_proto_notification_ui_proto_rawDescGZIP() []byte {
	file_proto_notification_ui_proto_rawDescOnce.Do(func() {
		file_proto_notification_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_ui_proto_rawDesc), len(file_proto_notification_ui_proto_rawDesc)))
	})
	return file_proto_notification_ui_proto_rawDescData
}

var file_proto_notification_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_notification_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_notification_ui_proto_goTypes = []any{
	(DriverStatus)(0),                        // 0: ui.DriverStatus
	(PassengerStatus)(0),                     // 1: ui.PassengerStatus
	(*Location)(nil),                         // 2: ui.Location
	(*DriverNotification)(nil),               // 3: ui.DriverNotification
	(*PassengerNotification)(nil),            // 4: ui.PassengerNotification
	(*PassengerNotification_DriverInfo)(nil), // 5: ui.PassengerNotification.DriverInfo
}
var file_proto_notification_ui_proto_depIdxs = []int32{
	0, // 0: ui.DriverNotification.status:type_name -> ui.DriverStatus
	2, // 1: ui.DriverNotification.pickup:type_name -> ui.Location
	2, // 2: ui.DriverNotification.dropoff:type_name -> ui.Location
	1, // 3: ui.PassengerNotification.status:type_name -> ui.PassengerStatus
	5, // 4: ui.PassengerNotification.driver:type_name -> ui.PassengerNotification.DriverInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_notification_ui_proto_init() }
func file_proto_notification_ui_proto_init() {
	if File_proto_notification_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_ui_proto_rawDesc), len(file_proto_notification_ui_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_ui_proto_goTypes,
		DependencyIndexes: file_proto_notification_ui_proto_depIdxs,
		EnumInfos:         file_proto_notification_ui_proto_enumTypes,
		MessageInfos:      file_proto_notification_ui_proto_msgTypes,
	}.Build()
	File_proto_notification_ui_proto = out.File
	file_proto_notification_ui_proto_goTypes = nil
	file_proto_notification_ui_proto_depIdxs = nil
}
