// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/notification_to_order.proto

package notification_orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event ที่ Notification Service ส่งไป Order Service.
// Keep field numbers compatible with order-service/proto/notification.proto
// (message OrderMatchNotification).
type OrderUpdateEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OrderId                 string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3"  json:"order_id,omitempty"`
	Status                  string                 `protobuf:"bytes,2,opt,name=status,proto3"  json:"status,omitempty"`
	DriverId                string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3"  json:"driver_id,omitempty"`
	DriverName              string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3"  json:"driver_name,omitempty"`
	DriverCarModel          string                 `protobuf:"bytes,5,opt,name=driver_car_model,json=driverCarModel,proto3"  json:"driver_car_model,omitempty"`
	DriverAvatarUrl         string                 `protobuf:"bytes,6,opt,name=driver_avatar_url,json=driverAvatarUrl,proto3"  json:"driver_avatar_url,omitempty"`
	CarPlate                string                 `protobuf:"bytes,7,opt,name=car_plate,json=carPlate,proto3"  json:"car_plate,omitempty"`
	CarType                 string                 `protobuf:"bytes,8,opt,name=car_type,json=carType,proto3"  json:"car_type,omitempty"`
	DriverLat               float64                `protobuf:"fixed64,9,opt,name=driver_lat,json=driverLat,proto3"  json:"driver_lat,omitempty"`
	DriverLng               float64                `protobuf:"fixed64,10,opt,name=driver_lng,json=driverLng,proto3"  json:"driver_lng,omitempty"`
	PickupLat               float64                `protobuf:"fixed64,11,opt,name=pickup_lat,json=pickupLat,proto3"  json:"pickup_lat,omitempty"`
	PickupLng               float64                `protobuf:"fixed64,12,opt,name=pickup_lng,json=pickupLng,proto3"  json:"pickup_lng,omitempty"`
	PickupAddress           string                 `protobuf:"bytes,13,opt,name=pickup_address,json=pickupAddress,proto3"  json:"pickup_address,omitempty"`
	DropoffLat              float64                `protobuf:"fixed64,14,opt,name=dropoff_lat,json=dropoffLat,proto3"  json:"dropoff_lat,omitempty"`
	DropoffLng              float64                `protobuf:"fixed64,15,opt,name=dropoff_lng,json=dropoffLng,proto3"  json:"dropoff_lng,omitempty"`
	DropoffAddress          string                 `protobuf:"bytes,16,opt,name=dropoff_address,json=dropoffAddress,proto3"  json:"dropoff_address,omitempty"`
	DistancePickupToDropoff float64                `protobuf:"fixed64,17,opt,name=distance_pickup_to_dropoff,json=distancePickupToDropoff,proto3"  json:"distance_pickup_to_dropoff,omitempty"`
	DurationTotal           int32                  `protobuf:"varint,18,opt,name=duration_total,json=durationTotal,proto3"  json:"duration_total,omitempty"`
	RoutePolyline           string                 `protobuf:"bytes,19,opt,name=route_polyline,json=routePolyline,proto3"  json:"route_polyline,omitempty"`
	Price                   float64                `protobuf:"fixed64,20,opt,name=price,proto3"  json:"price,omitempty"`
	Timestamp               int64                  `protobuf:"varint,21,opt,name=timestamp,proto3"  json:"timestamp,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrderUpdateEvent) Reset() {
	*x = OrderUpdateEvent{}
	mi := &file_proto_notification_to_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateEvent) ProtoMessage() {}

func (x *OrderUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_to_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateEvent.ProtoReflect.Descriptor instead.
func (*OrderUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_notification_to_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderUpdateEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderUpdateEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderUpdateEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OrderUpdateEvent) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *OrderUpdateEvent) GetDriverCarModel() string {
	if x != nil {
		return x.DriverCarModel
	}
	return ""
}

func (x *OrderUpdateEvent) GetDriverAvatarUrl() string {
	if x != nil {
		return x.DriverAvatarUrl
	}
	return ""
}

func (x *OrderUpdateEvent) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *OrderUpdateEvent) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *OrderUpdateEvent) GetDriverLat() float64 {
	if x != nil {
		return x.DriverLat
	}
	return 0
}

func (x *OrderUpdateEvent) GetDriverLng() float64 {
	if x != nil {
		return x.DriverLng
	}
	return 0
}

func (x *OrderUpdateEvent) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *OrderUpdateEvent) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *OrderUpdateEvent) GetPickupAddress() string {
	if x != nil {
		return x.PickupAddress
	}
	return ""
}

func (x *OrderUpdateEvent) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *OrderUpdateEvent) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

func (x *OrderUpdateEvent) GetDropoffAddress() string {
	if x != nil {
		return x.DropoffAddress
	}
	return ""
}

func (x *OrderUpdateEvent) GetDistancePickupToDropoff() float64 {
	if x != nil {
		return x.DistancePickupToDropoff
	}
	return 0
}

func (x *OrderUpdateEvent) GetDurationTotal() int32 {
	if x != nil {
		return x.DurationTotal
	}
	return 0
}

func (x *OrderUpdateEvent) GetRoutePolyline() string {
	if x != nil {
		return x.RoutePolyline
	}
	return ""
}

func (x *OrderUpdateEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_notification_to_order_proto protoreflect.FileDescriptor

const file_proto_notification_to_order_proto_rawDesc = "" +
	"\n" +
	"!proto/notification_to_order.proto\x12\x05order\"\xde\x05\n" +
	"\x10OrderUpdateEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x12(\n" +
	"\x10driver_car_model\x18\x05 \x01(\tR\x0edriverCarModel\x12*\n" +
	"\x11driver_avatar_url\x18\x06 \x01(\tR\x0fdriverAvatarUrl\x12\x1b\n" +
	"\tcar_plate\x18\a \x01(\tR\bcarPlate\x12\x19\n" +
	"\bcar_type\x18\b \x01(\tR\acarType\x12\x1d\n" +
	"\n" +
	"driver_lat\x18\t \x01(\x01R\tdriverLat\x12\x1d\n" +
	"\n" +
	"driver_lng\x18\n" +
	" \x01(\x01R\tdriverLng\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\v \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\f \x01(\x01R\tpickupLng\x12%\n" +
	"\x0epickup_address\x18\r \x01(\tR\rpickupAddress\x12\x1f\n" +
	"\vdropoff_lat\x18\x0e \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x0f \x01(\x01R\n" +
	"dropoffLng\x12'\n" +
	"\x0fdropoff_address\x18\x10 \x01(\tR\x0edropoffAddress\x12;\n" +
	"\x1adistance_pickup_to_dropoff\x18\x11 \x01(\x01R\x17distancePickupToDropoff\x12%\n" +
	"\x0eduration_total\x18\x12 \x01(\x05R\rdurationTotal\x12%\n" +
	"\x0eroute_polyline\x18\x13 \x01(\tR\rroutePolyline\x12\x14\n" +
	"\x05price\x18\x14 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x15 \x01(\x03R\ttimestampBYZWdift_backend_go/notification-service/proto/pb/notification_orderpb;notification_orderpbb\x06proto3"

var (
	file_proto_notification_to_order_proto_rawDescOnce sync.Once
	file_proto_notification_to_order_proto_rawDescData []byte
)

func file_proto_notification_to_order_proto_rawDescGZIP() []byte {
	file_proto_notification_to_order_proto_rawDescOnce.Do(func() {
		file_proto_notification_to_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_to_order_proto_rawDesc), len(file_proto_notification_to_order_proto_rawDesc)))
	})
	return file_proto_notification_to_order_proto_rawDescData
}

var file_proto_notification_to_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_notification_to_order_proto_goTypes = []any{
	(*OrderUpdateEvent)(nil), // 0: order.OrderUpdateEvent
}
var file_proto_notification_to_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_notification_to_order_proto_init() }
func file_proto_notification_to_order_proto_init() {
	if File_proto_notification_to_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_to_order_proto_rawDesc), len(file_proto_notification_to_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_to_order_proto_goTypes,
		DependencyIndexes: file_proto_notification_to_order_proto_depIdxs,
		MessageInfos:      file_proto_notification_to_order_proto_msgTypes,
	}.Build()
	File_proto_notification_to_order_proto = out.File
	file_proto_notification_to_order_proto_goTypes = nil
	file_proto_notification_to_order_proto_depIdxs = nil
}
